"""
Verification and sanity checks for generated content.

Checks:
- Every source page has a generated page file
- All tables have both HTML and (when applicable) normalized data
- No orphan images
- Front matter is complete
- Sections have reasonable page counts
- File naming consistency

Outputs verification_report.md to rs_smp_corpus/index/

Usage:
    python verify.py
"""

import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml


def load_config() -> dict[str, Any]:
    """Load configuration from config.yaml."""
    config_path = Path(__file__).parent / "config.yaml"
    with open(config_path, encoding="utf-8") as f:
        data: dict[str, Any] = yaml.safe_load(f)
        return data


def load_content_list(volume_path: Path) -> list[dict[str, Any]]:
    """Load content_list.json for a volume."""
    auto_dir = volume_path / "auto"
    json_files = list(auto_dir.glob("*_content_list.json"))
    json_files = [f for f in json_files if "_v2" not in f.name]

    if not json_files:
        return []

    with open(json_files[0], encoding="utf-8") as f:
        data: list[dict[str, Any]] = json.load(f)
        return data


class VerificationReport:
    """Collects verification results."""

    def __init__(self) -> None:
        self.issues: list[tuple[str, str]] = []
        self.warnings: list[tuple[str, str]] = []
        self.stats: defaultdict[str, int] = defaultdict(int)

    def add_issue(self, category: str, message: str) -> None:
        """Add a critical issue."""
        self.issues.append((category, message))

    def add_warning(self, category: str, message: str) -> None:
        """Add a warning."""
        self.warnings.append((category, message))

    def add_stat(self, key: str, value: int = 1) -> None:
        """Add to statistics counter."""
        self.stats[key] += value

    def write_report(self, filepath: Path) -> None:
        """Write verification report to file."""
        filepath.parent.mkdir(parents=True, exist_ok=True)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Verification Report\n\n")
            f.write("Generated by verify.py\n\n")

            # Summary
            f.write("## Summary\n\n")
            f.write(f"- **Issues (Critical):** {len(self.issues)}\n")
            f.write(f"- **Warnings:** {len(self.warnings)}\n\n")

            # Statistics
            f.write("## Statistics\n\n")
            for key in sorted(self.stats.keys()):
                f.write(f"- **{key}:** {self.stats[key]}\n")
            f.write("\n")

            # Issues
            if self.issues:
                f.write("## Issues (Critical)\n\n")
                by_category: defaultdict[str, list[str]] = defaultdict(list)
                for cat, msg in self.issues:
                    by_category[cat].append(msg)

                for cat in sorted(by_category.keys()):
                    f.write(f"### {cat}\n\n")
                    for msg in by_category[cat]:
                        f.write(f"- {msg}\n")
                    f.write("\n")
            else:
                f.write("## Issues\n\n✓ No critical issues found.\n\n")

            # Warnings
            if self.warnings:
                f.write("## Warnings\n\n")
                by_category = defaultdict(list)
                for cat, msg in self.warnings:
                    by_category[cat].append(msg)

                for cat in sorted(by_category.keys()):
                    f.write(f"### {cat}\n\n")
                    for msg in by_category[cat]:
                        f.write(f"- {msg}\n")
                    f.write("\n")
            else:
                f.write("## Warnings\n\n✓ No warnings.\n\n")


def verify_pages(
    volume_config: dict[str, Any], base_path: Path, report: VerificationReport
) -> None:
    """Verify page generation for a volume."""
    volume_id = volume_config["id"]
    volume_folder = volume_config["folder"]

    print(f"  Verifying pages for {volume_id}...")

    # Load source content list
    volume_path = base_path / volume_folder
    content_list = load_content_list(volume_path)

    if not content_list:
        report.add_issue("Pages", f"{volume_id}: Could not load content_list.json")
        return

    # Get unique page indices
    source_pages = set(
        e.get("page_idx") for e in content_list if e.get("page_idx") is not None
    )

    # Check generated pages
    pages_dir = base_path / "rs_smp_corpus" / "volumes" / volume_id / "pages"
    if not pages_dir.exists():
        report.add_issue("Pages", f"{volume_id}: pages/ directory missing")
        return

    generated_pages = set()
    for page_file in pages_dir.glob("p*.md"):
        match = re.match(r"p(\d+)_", page_file.name)
        if match:
            generated_pages.add(int(match.group(1)))

    # Compare
    missing = source_pages - generated_pages
    extra = generated_pages - source_pages

    if missing:
        report.add_warning(
            "Pages", f"{volume_id}: {len(missing)} source pages not generated"
        )

    if extra:
        report.add_warning(
            "Pages", f"{volume_id}: {len(extra)} generated pages not in source"
        )

    report.add_stat(f"{volume_id}_pages_source", len(source_pages))
    report.add_stat(f"{volume_id}_pages_generated", len(generated_pages))


def verify_tables(volume_id: str, base_path: Path, report: VerificationReport) -> None:
    """Verify tables for a volume."""
    print(f"  Verifying tables for {volume_id}...")

    tables_dir = base_path / "rs_smp_corpus" / "volumes" / volume_id / "tables"
    if not tables_dir.exists():
        report.add_warning("Tables", f"{volume_id}: tables/ directory missing")
        return

    table_count = 0
    xy_list_count = 0
    xy_titleblock_count = 0
    incomplete_xy_lists = 0

    for table_file in tables_dir.glob("*.md"):
        table_count += 1

        with open(table_file, encoding="utf-8") as f:
            content = f.read()

            # Check for front matter
            if not content.startswith("---"):
                report.add_issue(
                    "Tables", f"{volume_id}/{table_file.name}: Missing front matter"
                )
                continue

            # Check for HTML table
            if "```html" not in content:
                report.add_warning(
                    "Tables", f"{volume_id}/{table_file.name}: Missing HTML section"
                )

            # Title-block-only tables are expected to have no normalized data
            if "xy-list-titleblock" in table_file.name:
                xy_titleblock_count += 1
                continue

            # For XY-lists with real data, check for normalized data or designators
            if "xy-list" in table_file.name:
                xy_list_count += 1
                has_full = "## Normalized Component Data" in content
                has_partial = "## Component Designators (Partial Extraction)" in content
                if not has_full and not has_partial:
                    incomplete_xy_lists += 1
                    report.add_warning(
                        "Tables",
                        f"{volume_id}/{table_file.name}: XY-list missing normalized data",
                    )

    report.add_stat(f"{volume_id}_tables_total", table_count)
    report.add_stat(f"{volume_id}_tables_xy_lists", xy_list_count)
    report.add_stat(f"{volume_id}_tables_xy_titleblocks", xy_titleblock_count)

    if incomplete_xy_lists > 0:
        report.add_stat(f"{volume_id}_tables_incomplete", incomplete_xy_lists)


def verify_figures(volume_id: str, base_path: Path, report: VerificationReport) -> None:
    """Verify figures for a volume."""
    print(f"  Verifying figures for {volume_id}...")

    figures_dir = base_path / "rs_smp_corpus" / "volumes" / volume_id / "figures"
    if not figures_dir.exists():
        report.add_warning("Figures", f"{volume_id}: figures/ directory missing")
        return

    # Count stubs and images
    stub_count = len(list(figures_dir.glob("p*.md")))
    image_count = len(list(figures_dir.glob("p*.jpg")))

    # Check for orphans
    stubs = {f.stem for f in figures_dir.glob("p*.md")}
    images = {f.stem for f in figures_dir.glob("p*.jpg")}

    orphan_stubs = stubs - images
    orphan_images = images - stubs

    if orphan_stubs:
        report.add_warning(
            "Figures", f"{volume_id}: {len(orphan_stubs)} stub(s) without image"
        )

    if orphan_images:
        report.add_warning(
            "Figures", f"{volume_id}: {len(orphan_images)} image(s) without stub"
        )

    report.add_stat(f"{volume_id}_figure_stubs", stub_count)
    report.add_stat(f"{volume_id}_figure_images", image_count)


def verify_sections(
    volume_id: str, base_path: Path, report: VerificationReport
) -> None:
    """Verify sections for a volume."""
    print(f"  Verifying sections for {volume_id}...")

    sections_dir = base_path / "rs_smp_corpus" / "volumes" / volume_id / "sections"
    if not sections_dir.exists():
        report.add_warning("Sections", f"{volume_id}: sections/ directory missing")
        return

    section_count = 0

    for section_file in sections_dir.glob("*.md"):
        section_count += 1

        with open(section_file, encoding="utf-8") as f:
            content = f.read()

            # Check front matter
            if not content.startswith("---"):
                report.add_issue(
                    "Sections", f"{volume_id}/{section_file.name}: Missing front matter"
                )
                continue

            # Parse front matter
            parts = content.split("---", 2)
            if len(parts) >= 3:
                try:
                    front_matter = yaml.safe_load(parts[1])
                    n_pages = front_matter.get("n_pages", 0)

                    # Warn if section is suspiciously small or large
                    if n_pages < 1:
                        report.add_warning(
                            "Sections", f"{volume_id}/{section_file.name}: No pages"
                        )
                    elif n_pages > 200:
                        report.add_warning(
                            "Sections",
                            f"{volume_id}/{section_file.name}: Very large ({n_pages} pages)",
                        )
                except Exception:
                    report.add_issue(
                        "Sections", f"{volume_id}/{section_file.name}: Invalid YAML"
                    )

    report.add_stat(f"{volume_id}_sections", section_count)


def main() -> None:
    """Main entry point."""
    print("Running verification checks...\n")

    # Find project root
    base_path = Path(__file__).parent.parent

    # Load configuration
    config = load_config()

    # Initialize report
    report = VerificationReport()

    # Verify each volume
    for volume_config in config["volumes"]:
        volume_id = volume_config["id"]
        print(f"Checking {volume_id}...")

        try:
            verify_pages(volume_config, base_path, report)
            verify_tables(volume_id, base_path, report)
            verify_figures(volume_id, base_path, report)
            verify_sections(volume_id, base_path, report)
        except Exception as e:
            report.add_issue("General", f"{volume_id}: Verification failed: {e}")
            import traceback

            traceback.print_exc()

    # Write report
    report_path = base_path / "rs_smp_corpus" / "index" / "verification_report.md"
    report.write_report(report_path)

    print("\n✓ Verification complete!")
    print(f"  Report: {report_path}")
    print(f"  Issues: {len(report.issues)}")
    print(f"  Warnings: {len(report.warnings)}")

    # Exit with error code if issues found
    if report.issues:
        sys.exit(1)


if __name__ == "__main__":
    main()
